# Versão
version: "3.7"

services: 
  database_ignite:
    image: postgres
    container_name: database_ignite
    restart: always
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres

  # Nome do serviço
  app: 
    # Gera o build no diretório local
    build: .
    # Nome do container
    container_name: rentx
    # Compartilhamento de portas
    ports:
      - 3333:3333
    # Comartilhar diretório
    volumes:
      # Tudo do local para o /usr/app
      - .:/usr/app

volumes:
  pgdata: